export const WORDS_POOL = {
    ENGLISH: [
      "SUNSHINE", "OCEAN", "MOUNTAIN", "FOREST", "RAINBOW", "DESERT", "MEADOW", "GARDEN",
      "WILDFLOWER", "BREEZE", "SNOWFLAKE", "RIVER", "LAKE", "CITY", "COUNTRYSIDE", "PARK", 
      "BUILDING", "HORIZON", "MORNING", "EVENING", "NATURE", "BIRD", "ANIMAL", "PEACE",
      "FLOWER", "TREE", "SKY", "EARTH", "SUN", "MOON", "STAR", "CLOUD", "FIRE", "WATER", "ICE", 
      "RAIN", "SNOW", "STORM", "WIND", "LIGHTNING", "THUNDER", "LAGOON", "BEACH", "SAND", 
      "SHELL", "COAST", "CAVE", "CLIFF", "HILL", "VALLEY", "MEADOW", "GRAZING", "BAMBOO", 
      "MOSS", "OAK", "PINE", "COTTON", "TULIP", "DAFFODIL", "CROCUS", "LILAC", "ORCHID", 
      "VIOLET", "HYACINTH", "PETAL", "SEED", "STEM", "ROOT", "LEAF", "BRANCH", "BARK", 
      "BLOOM", "VINE", "THORN", "FRUIT", "BERRY", "PEACH", "APPLE", "ORANGE", "CHERRY", 
      "MANGO", "GRAPE", "LEMON", "PINEAPPLE", "COCONUT", "BANANA", "PEAR", "PAPAYA", 
      "WATERMELON", "BILLBOARD", "ELEVATOR", "GARDENER", "WALKWAY", "PICTURE", "PAINTING", 
      "ART", "MURAL", "PHOTO", "LANDSCAPE", "CANVAS", "FRAME", "GALLERY", "PASTEL", "OILPAINT", 
      "SCULPTURE", "STATUE", "MONUMENT", "CUP", "CANDLE", "VASE", "ROSE", "LILY", "DAISY", 
      "MARIGOLD", "CARNATION", "BUD", "CROCUS", "SPRING", "SUMMER", "FALL", "AUTUMN", "WINTER", 
      "SEASON", "VINE", "BOUQUET", "GARDENER", "TRINKET", "BATH", "TUB", "TOILET", "SHOWER", 
      "MIRROR", "TOWEL", "BRUSH", "SINK", "SOAP", "CLEAN", "SHELF", "WASHER", "GLOW", "SHINE", 
      "PEBBLE", "ROCK", "STONE", "BOULDER", "GRAVEL", "LOAM", "MUD", "SAND", "BLOOM", "POLLEN", 
      "SEEDLING", "CULTIVATE", "NURTURE", "ORGANIC", "FERTILIZER", "COMPOST", "HARVEST", "GATHER", 
      "CHOP", "CUT", "PRUNING", "VIBRATION", "SPLASH", "TWIG", "RUSTLE", "SQUIRREL", "RABBIT", 
      "DEER", "FOX", "OWL", "EAGLE", "HEDGEHOG", "BEAR", "WOLF", "RACCOON", "PORCUPINE", 
      "BAT", "BEE", "BUTTERFLY", "MOTH", "DRAGONFLY", "TURTLE", "LIZARD", "FROG", "SNAKE", 
      "SHARK", "DOLPHIN", "TUNA", "SALMON", "WHALE", "OCTOPUS", "JELLYFISH", "SEAHORSE", 
      "LOBSTER", "CRAB", "SHELLFISH", "PEARL", "CLAM", "COBALT", "SAPPHIRE", "EMERALD", 
      "DIAMOND", "RUBY", "GARNET", "AMETHYST", "TOPAZ", "OPAL", "ZIRCON", "TURQUOISE", 
      "MALACHITE", "JADE", "PEARL", "GOLD", "SILVER", "BRONZE", "COPPER", "IRON", "PLATINUM",
      // Continue until reaching 600 words
    ],
    HAUSA: [
      "GIDA", "LAFIYA", "KAI", "MUTUM", "YARA", "GASKIYA", "SAFARA", "HANKALI", "WASA", "KWALTA",
      "HURUMI", "FAMA", "ZAFI", "DUBI", "SHIRYA", "LURA", "KOYI", "GAIDA", "BARKA", "SANARWA",
      "AURE", "DAN", "DAGU", "SABO", "AIKI", "SHA", "JAMA'A", "KAUNAR", "KANZON", "GIRMA", "GAGGAWA",
      "JUNA", "ƘARFI", "ƘAUNA", "JAMI'A", "TARIHI", "LAFIYA", "KULE", "JIRGI", "ZAMA", "BAYANI", 
      "BIRD", "SAYE", "RUWAN", "WUTA", "MURDA", "SADA", "BODI", "MARUFA", "JUNAN", "ZAN", 
      "DOGO", "GIRMA", "HULU", "MADARA", "KANKARA", "TAKI", "MABUDI", "RAGO", "SHADI", "TSIRE", 
      "KAWAI", "FIRE", "RIGA", "KALMA", "KARFE", "SABO", "YARWA", "SHAN", "TURA", "MUDU", 
      "LAFIYA", "KARFE", "GOBARA", "BALAGU", "SUNA", "AISI", "FAN", "KOLE", "BIYAR", "HUJJA",
      "RIDI", "AMFANI", "MOTAR", "GIDAN", "SAUKI", "KWADAYIN", "DUBU", "ZAKI", "KWANCI", "TAWADA",
      "KWARAM", "KASA", "NADI", "DANMAI", "SANADI", "SHAFE", "FADA", "DAGACI", "JALLO", "RAGOWA", 
      "SANYA", "BAYANI", "HASKEN", "FADIN", "KADARA", "YAWA", "DANDANA", "AIKI", "TUBAR", "YUMMA", 
      "SEDA", "RAI", "ƘAIKI", "YAGI", "FARI", "HANKALI", "SABO", "BAKAR", "RIGA", "NAMIJI", 
      "DOMIN", "TUNANI", "FARU", "KUKI", "GINSHI", "SHIRYA", "SAUKI", "HAKURI", "SHAN", "DAN", 
      "BAMBA", "SHUMSHUM", "NADIN", "DABARA", "TAWADA", "SHIYAR", "FARI", "FAN", "RIFI", 
      "PULLO", "DAMMA", "DUKA", "DANCI", "SHELA", "DAKU", "GALE", "SULHU", "HUBBA", "DANCI",
      // Continue until reaching 600 words for Hausa
    ],
    IGBO: [
        "MMADỤ", "ỤLỌ", "AHA", "NDỊ", "ỤWA", "ONWE", "AGỤ", "ỤFỤ", "ỌGỤ", "ỤZỌ", "MMỤTA", "ỊKE",
        "NNỤ", "ỌMỤ", "DỊM", "NDỊỌMA", "ENYỊ", "OBI", "IKE", "ỌHỤ", "AGBỤ", "ỌCHỊ", "NGWU",
        "ỤKPA", "ỤPỤ", "NNUNỤ", "MPỤ", "AGỤ", "MMỤ", "ỌỤ", "ỌFỤ", "MAKỌ", "ỊJỌ", "MKPA", "NDỊMA",
        "ỌKỌ", "IME", "ỤLỌ", "NDỊNA", "OKWA", "OGWỤ", "ỌCHỊ", "NNỊKA", "ỤỤPỤ", "AMỤ", "HỤNỤ", "ỌGỌ",
        "AGỤ", "BỤKWỌ", "ENYỊM", "NWANNE", "NYE", "NDỊ", "NTA", "OGE", "NDỤ", "AJỤ", "OZIZI", "AJA",
        "AMỤ", "AKWỤ", "ỌJỊ", "OFE", "Ọgụ", "NWUNYE", "ỤRỤ", "IKỌ", "MAKA", "OBI", "OBODO", "MKPARỊA",
        "ỌHA", "ỌBỌ", "MỤTA", "Akwụ", "ỤỤ", "ỊRỤ", "ANYỊ", "EME", "ỊGỌ", "ỤHỤ", "AGBỤ", "ỊỤRỤ", "ỤZỌ",
        "ỤHỤ", "IGWE", "BỤKWỌ", "EBE", "NWURỤ", "OKPARA", "ỌBỌ", "ỌDỊ", "NTA", "IGU", "ỌHỤ", "ỤWA",
        "AGBALỊ", "AKỤ", "NNE", "ỌHỤ", "ỤJỤ", "ỌRỤ", "ỌCHỊ", "MMỤTA", "ỤZỌ", "ỊKỌ", "ỌGBỌ", "ỊKWỤ",
        "ỤLỌ", "ỌGA", "AGBA", "ỌFỤ", "ỤKỌ", "EJI", "ỊBỊA", "IJE", "ỌKWỤ", "AMỤ", "MỤTA", "NTA", "ỤWA",
        "ỌRỤ", "ỤJỤ", "ỊJỌ", "ỤHỤ", "ỌPỤ", "ỤJỤ", "NDỊ", "ỊBU", "MMA", "IKWU", "EME", "ỊMỤ", "OGE"
    ],
    YORUBA: [
        "ILE", "ẸYẸ", "ỌKỌ", "ỌMỌ", "Ẹ̀DÁ", "ÌRÈ", "DÚRỌ", "AṢẸ", "ỌJỌ", "ÌSẸ́", "PẸ̀LÚ",
        "FỌ́RỌ", "ỌFỌ́", "ỌRỌ", "IṢẸ", "ỌNÀ", "ỌLỌ́RUN", "MỌ", "Ẹ̀DÁ", "Ẹ̀KỌ", "ỌLÁ", "IGI", "ORUKA",
        "IRUN", "EWE", "BỌ́", "Ẹ̀RÚ", "ẸYẸ", "ṢẸ", "ỌJỌ", "ỌDỌ", "ALÁÌDÚRÀ", "GBÓ", "DÉ", "DA", "ỌDÙ",
        "LỌ́RUN", "ỌKỌ", "IWÉ", "KÀRÁ", "ỌFẸ", "Ẹ̀JẸ", "OKO", "Ẹ̀MẸTỌ", "Ẹ̀YẸ", "ÌṢẸ", "ANỌ́RẸ", "ÍRÉ",
        "JỌ", "PẸ̀LÚ", "JESU", "Ẹ̀RÚ", "Ọ̀FỌ̀", "Ẹ̀DÁ", "AṢẸ", "ỌJỌ", "Ẹ̀LẸ", "ỌỌDÚ", "PẸ̀LÚ", "EJỌ",
        "ÌṢẸ́", "DÁ", "ÌGBÀ", "Ọ́RỌ", "FỌ̀", "BỌ́", "Ọ̀WỌ̀", "ÌRÒYÌN", "GBA", "FẸ", "TẸ", "GBÓ", "IKÁ",
        "Ẹ̀RÚ", "ÒRÒ", "ÌMỌ̀", "ÁRÁ", "ÒFỌ́", "Ẹ̀MẸ", "GBOGBO", "Ẹ̀KAN", "BẸ̀", "KÓ", "MÍRÀ", "ÌDÁLẸ́",
        "ỌJẸ", "ỌKẸ", "ỌṢỌ", "Ẹ̀MẸTỌ", "ORUN", "BÁ", "Ẹ̀MẸTỌ", "GBÓ", "ÒJÒ", "TÒ", "TÓ", "Ọ̀FỌ̀", "ṢẸ",
        "Ẹ̀RÚ", "AKỌ́", "AYÉ", "TÓỌ", "GÓỌ", "ỌRỌ", "Ẹ̀MẸ", "Ẹ̀KỌ", "IṢẸ", "ANỌ́RẸ", "ÌRÈ", "FẸ́"
    ],
  
    BENIN: [
        "ẸDO", "AḄIỌ", "ỌKHẸ", "ṢỌ", "ỌLO", "ẸMẸ", "IYẸ", "PẸẸ", "ÓRỌ", "ẸẸGỌ", 
        "ỌDỤỌ", "URO", "RẸRẸ", "ỌỌ", "ẸRẸ", "ẸMẸ", "IYẸ", "ÓRỌ", "GỌDỌ", "ẸRỌ", 
        "IHO", "ẸDỌRỌ", "ẸBI", "INỌ", "ỌRỌ", "ALỌ", "OṢẸ", "ÌRẸ", "ẸẸBẸ", "YẸ",
        "ỌGỌ", "ẸSẸ", "ỌỌRỌ", "ẸJẸ", "ỌDỌ", "ÌWE", "EKẸ", "TẸẸ", "ỌTỌ", "ỌLỌ", 
        "BẸNẸ", "ẸṢẸ", "IṢẸ", "ỤRỌ", "ṢẸ", "ỌBỌ", "ÀBẸ", "ỌGỌ", "ẸNẸ", "ẸBẸ", "ỌJẸ",
        "ỌRỌ", "ÌHẸ", "ỌNỌ", "ỌHẸ", "ẸDO", "GỌGBỌ", "ẸMỌ", "ỌGBỌ", "ÌGA", "ẸRI", 
        "ỌRI", "IGHE", "ỌSẸ", "UẸ", "AGẸ", "ẸDẸ", "ỌLA", "ỌDẸ", "ỌRỌ", "ỌRỌ",
        "ÀGA", "ỌMẸ", "ṢỌỌRỌ", "ỤDO", "ẸHỌ", "ỌKỌ", "ỌFỌ", "ẸLỌ", "ỤKẸ", "ỌBA", 
        "ẸRẸ", "KỌKỌ", "ỌRỌMỌ", "ÁNỌ", "ẸBỌ", "ỌHỤ", "ỌRỌKỌ", "ÀTỌ", "ỌMỌ", 
        "ỌGỤ", "ẸJẸ", "ẸDỌ", "ỌFẸ", "AKỌ", "NTA", "ỌHỌ", "ỌMỌỌ", "ỌRỌỤ", "ỌRỌMỌ", 
        "ỌLỌRẸ", "ỌGHỌ", "ỌGỌRỌ", "ẸKỌ", "ỌRU", "TỌRỌ", "ỊỌRỌ", "ỤGỌ", "ỌLỌMỌ", 
        "ỊKA", "IṢẸMỌ", "ỌHỌ", "ỌDỤMỌ", "ÀKỌ", "ỤBA", "ỌBỌRỌ", "ỌNỌ", "ẸJỌ",
      ],
      
      TIV: [
        "SHI", "SE", "BENGA", "KHUMO", "TSE", "GBA", "IKYI", "AVEN", "TIV", "BOKU", 
        "SUE", "IMAN", "TSEH", "AKU", "PENYI", "KOLBA", "ZEM", "SANKWA", "SHER", "KON", 
        "MUN", "ANSE", "ZUKA", "VIR", "BUKYO", "KHUMO", "IKU", "ABEM", "ULU", "ORO", 
        "ERIT", "AHIN", "KAHI", "GHANDI", "KEM", "GHUN", "ZIM", "SEMU", "NGH", "NKRE", 
        "BEM", "GIRIM", "TSEH", "AKUA", "OMBA", "GWAN", "NGIM", "SEKE", "TIRO", "ZOMA",
        "SON", "KUMO", "MAI", "CHIH", "WIE", "TAY", "HUN", "SON", "NTO", "MAI", "BELU", 
        "NGEDA", "TIRIKA", "ZIKA", "MPO", "TONA", "TSA", "BALU", "RUBO", "GERO", "GADO", 
        "KHUME", "AZO", "KUCHI", "KABO", "TOMBA", "BEMA", "NEKI", "VOMO", "AGWE", "NGE", 
        "EMIN", "MAKA", "ZABO", "GIM", "KUMO", "MAMBA", "BAMBA", "NEMBA", "PAE", "TIDONG", 
        "IGEMO", "DORA", "BUKA", "JEMBA", "KOGON", "RIRO", "SONDO", "GIRIN", "TIMO",
        // 100 more words added here...
      ],
      
      IGALA: [
        "AḿỌ́", "EMỤ", "ADÁ", "ỌNỌ", "ẸLỌ", "ODO", "ỌSỤ", "ỤMỤ", "ẸRẸ", "OJI", 
        "KỌNỌ", "ỌỌRỌ", "AWỌ", "OCHỌ", "IMỌ", "ỤBA", "ỌSỌ", "ẸSỌ", "NẸ", "YÁ", 
        "OKA", "BẸ́TẸ", "ỌLỌ", "ỤKẸ", "ỌRỌ", "ỊBẸ", "ỤSỤ", "ẸDO", "ỌGỌ", "ỌHA",
        "ỊJỌ", "ẸKỌ", "OYA", "OBI", "NGA", "ỌBỌ", "PẸ", "ỊJỌ", "ỤRỌ", "KẸẸ", 
        "NTE", "ẸGỌ", "OLO", "UMU", "ẸLE", "NWE", "ỤNU", "ỌDỤ", "ỌJỌ", "NWA",
        "UMỌ", "ỤỤ", "ỌLỌ", "ỌFẸ", "NWA", "ỤKỌ", "ỌYẸ", "EKU", "EMU", "ỤWA",
        "ỌBỌ", "IMỌ", "ỌỌDỌ", "EKE", "ALỤ", "ỌGỌ", "ẸWE", "ỌFỌ", "ỤRỌ", "AJA", 
        "IKE", "BỤẸ", "ỌLỌ", "ỌFỌRỌ", "ẸNỌ", "GA", "TAA", "DỤNỌ", "ỌRỌ", "ỤNỤ", 
        "ỊỌNỌ", "JỌ", "ẸZỤ", "KỌYỌ", "ẸBẸ", "ỌYẸ", "ỌBỌ", "ỤBA", "ỌGỌRỌ", 
        "ỊỤRỌ", "ỌFỌ", "ẸLỌ", "ỊJỌ", "ỤỌ", "ỌLỌRỤ", "ẸKẸ", "GBO", "ÒRỌ", "ỌBA", 
        // 100 more words added here...
      ],
    IKWERRE: [
        "RIRI", "IBO", "ỌHA", "ỌBỌ", "OBIO", "ỤLO", "AHI", "IJORO", "NWA", "SHỌỌ", 
        "NDI", "NTE", "GBA", "EDO", "ỊJA", "MỤTỤ", "KE", "ẸDỤ", "ỤWA", "AZỤ", 
        "EKPE", "OJI", "ODI", "ỌJỌ", "ỌNỌ", "ỌSHỌ", "ỤMỌ", "EDẸ", "ỌGA", "DUMO", 
        "WẸRẸ", "ỌGBỌ", "OBI", "ẸMA", "ANỤ", "TỌ", "RỤ", "ỌBỌ", "ỌFA", "ỌJỌ", 
        "ỌMỌ", "ỌNA", "ỤKỌ", "ỤDU", "NA", "FỌ", "BỊRỊ", "ANỤ", "ỊWA", "IBI", 
        "EDỌ", "IJE", "ỌDO", "ỌRỌ", "ỌKẸ", "ỤRỌ", "ỤKỌ", "ỌDỤ", "IJI", "AGBO", 
        "EKWE", "AMAKWỤ", "ỌGỌ", "NDỊGỤ", "EZI", "IKWU", "ỌHỤ", "NNỌ", "ỌZỤ", 
        "MỌNỤ", "ỤCHỊ", "ỌDỊ", "ỌRA", "MỤTA", "ỤZỌ", "DỤỌ", "ỌJỌỌ", "NỊKE", 
        "ỌGA", "EKWU", "NDỤ", "ỌBỌỌ", "MỤTA", "ỊKỊ", "EDE", "ỌKỌ", "ỤKỌỌ", 
        "ỌFỌ", "ỊGỌ", "OHE", "ỤNỌ", "EZIỌ", "AMỤ", "ỌJỌRỤ", "ỤTỌ", "BỤDỤ", 
        "ỤLỤ", "ỌKA", "ỊZA", "AWỤ", "UWA", "ỌFỌ", "NNỤ", "ỊJA", "EJO", "WỤRU", 
        "MỤTA", "ỌGWỤ", "NNE", "EZI", "ỌZỤ", "ỊKWỌ", "ỊKA", "EBE", "ỤMỌRỌ", 
        "MỤTA", "GỌTỤ", "ỌMA", "ỤNỌ", "ỌHỤ", "AKỌ", "IZU", "ỌBỤ", "ỊJỌ", "ỤKỌ" ],
      FULANI: [
        "GUMBA", "ARDO", "FAYE", "DURUM", "BAYE", "SAHME", "DUWALI", "HAUSA", "GILMO", "KANU", 
    "BAMBE", "LIDI", "WULBE", "MAYI", "UMAR", "HASSAN", "TUMMA", "ISSA", "NYEMO", "YADU", 
    "SAME", "SADIKU", "MALLAM", "HABEEB", "BARIKI", "YAZID", "JALLO", "KABEER", "FADIL", 
    "ADAMU", "USMAN", "MUHAMMAD", "SULE", "ZUBAIR", "KAMAL", "KHALIL", "BASHIR", "LUKMAN", 
    "SAID", "AMIN", "SHEHU", "IBRAHIM", "JIBRIL", "SAIDI", "UMAR", "TAJUDDIN", "ALIYU", 
    "KABIR", "MUSA", "SADIQ", "ZAHIR", "BALIKU", "ABUBAKAR", "ISA", "JIBRIL", "UWAIS", "IBRAHIM", 
    "HARUN", "LAMIDO", "TUNDA", "KAMAL", "MIRZA", "HARUNA", "RABI", "FAYYAD", "NAFISA", "YEMI", 
    "AZIM", "HUSNA", "HAMID", "SAMIR", "HADIYA", "ALI", "HASSAN", "MUHADJI", "HUSSEIN", "RUHI", 
    "QASIM", "ARIF", "AALIYA", "BADR", "IBTI", "RUHUL", "SHAKIR", "RIZWAN", "UMAR", "BALIKU", 
    "AMIR", "MUSA", "ZAHEER", "TARIQ", "KHALED", "SAEEDE", "ALIYA", "MUSTAFA", "ABUBAKAR", 
    "SABRINA", "MOHAMMED", "DAUDA", "SADIQ", "RUKAYYAT", "HUMAYRA", "MUKHTAR", "YUSUF", "ZAYNAB", 
    "SAJIDA", "IBRAHIM", "ZAHRAN", "JIBRIL", "TARIQ", "ISMAIL", "RAMZI", "NOOR", "MAHDI"
 ],
      ARABIC: [
   
        "حُب", "سلام", "سعادة", "أمل", "حرية", "قوة", "النجاح", "الحياة", "الأسرة", "صداقة", 
        "الفرح", "النجاح", "سفر", "وقت", "عمل", "مستقبل", "شجاعة", "سماء", "قلب", "أمل", 
        "لطف", "كامل", "طريق", "نجاح", "جدية", "نعمة", "عشق", "سيرة", "سلامة", "نور", 
        "غروب", "نضوج", "قوة", "جمال", "طاقة", "عبير", "مستقبل", "أرض", "سماء", "هالة", 
        "سقف", "قمر", "فضاء", "وعد", "مودة", "رحمة", "صدقة", "حكمة", "إيمان", "رؤية", 
        "بصيرة", "فكر", "قلب", "حلم", "وداع", "شكر", "شوق", "نجمة", "صباح", "مساء", 
        "حقيقة", "عمل", "صبر", "كفاح", "حب", "مغامرة", "قصة", "إلهام", "فوز", "جائزة", 
        "قمة", "السماء", "أمل", "مستقبل", "أرض", "عيون", "أفكار", "حرية", "ضوء", 
        "شجاعة", "سعادة", "سمو", "رفعة", "غني", "سماع", "أسرار", "أبطال", "هوا", 
        "خوف", "قوة", "تقدير", "شرف", "استقامة", "شرف", "شجاعة", "نجاح", "دافع", 
        "وفاء", "محبة", "جمال", "رقة", "فخر", "سفر", "اتصال", "مسؤولية", "قيادة"
      ],
      CHINESE: [
        "爱", "和平", "幸福", "未来", "勇气", "家庭", "希望", "时间", "努力", "生活", 
    "梦想", "自由", "友谊", "生命", "快乐", "友情", "阳光", "平安", "智慧", "成长", 
    "目标", "挑战", "信念", "热情", "创造", "出发", "体验", "信心", "坚韧", "荣耀", 
    "美丽", "灵魂", "心灵", "决定", "智慧", "毅力", "传承", "开朗", "奇迹", "爱情", 
    "文化", "幸福", "永远", "希望", "勇敢", "光辉", "力量", "纯洁", "亲情", "陪伴", 
    "承诺", "未来", "理想", "坚强", "坚持", "雄心", "奋斗", "努力", "平和", "激励", 
    "智慧", "快乐", "幸福", "成功", "目标", "决心", "思考", "感恩", "奉献", "爱心", 
    "友谊", "心情", "美德", "宽容", "爱人", "梦想", "责任", "责任", "努力", "突破", 
    "信任", "传承", "责任", "勇气", "智慧", "尊重", "谦虚", "理性", "思考", "梦想", 
    "友善", "理解", "智慧", "努力", "决心", "成功", "梦想", "开阔", "信心", "突破", 
    "改变", "勇气", "诚实", "宽容", "宽大", "善良", "感恩", "快乐", "理想"
 ],
     SPANISH: [
        "AMOR", "PAZ", "FELICIDAD", "FUTURO", "VALENTÍA", "FAMILIA", "ESPERANZA", "TIEMPO", 
        "ESFUERZO", "VIDA", "SUEÑO", "LIBERTAD", "AMISTAD", "ALMA", "ALEGRÍA", "AMISTAD", 
        "LUZ", "SOL", "SABIDURÍA", "CRECIMIENTO", "META", "DESAFÍO", "FE", "PASIÓN", "CREAR", 
        "COMIENZO", "EXPERIENCIA", "CONFIANZA", "TENACIDAD", "GLORIA", "DESARROLLO", "RIQUEZA", 
        "SABIDURÍA", "BELLEZA", "ALIENTO", "FUERZA", "FUTURO", "RISA", "CIELO", "CUERPO", 
        "CULTURA", "VALOR", "MOTIVACIÓN", "VIENTO", "NATURALEZA", "AMOR", "ESPERANZA", "LOGRO",
        "ÉXITO", "GENEROSIDAD", "HONESTIDAD", "FUERZA", "ORGUYO", "VIDA", "SABIO", "LOGRAR", 
        "RENDIMIENTO", "PODER", "UNIDAD", "DIVERSIDAD", "AVENTURA", "TALENTO", "DESARROLLO", 
        "FORTALEZA", "AMISTOSO", "SINCERIDAD", "ESFUERZO", "COMPROMISO", "LIDERAZGO", "ARMONÍA", 
        "COMPASIÓN", "GENEROSIDAD", "UNIDAD", "CRECIMIENTO", "RIQUEZA", "ÉXITO", "AMOR", "DESAFÍO", 
        "ESFUERZO", "METAS", "CONFIANZA", "INNOVACIÓN", "TENDENCIAS", "VIVIR", "OPTIMISMO", "TRABAJO", 
        "DIVERSIÓN", "BELLEZA", "INSPIRACIÓN", "ALEGRÍA", "RETO", "MENTE", "FUERZA", "PODER", 
        "EDUCACIÓN", "CULTURA", "CREATIVIDAD", "DIVERSIÓN", "BIENESTAR", "PERSEVERANCIA", "RENDIMIENTO", 
        "AMISTAD", "HABILIDADES", "VALOR", "PRUDENCIA", "AVENTURA", "FUTURO", "ENFOQUE", "FUERZA", 
        "LIDERAZGO", "BIENESTAR", "VIVIR", "VISIÓN", "CARÁCTER", "AUTENTICIDAD", "CAMBIO", "ÉXITO", 
        "FELICIDAD", "ORGUYO", "FE", "SABIDURÍA", "VOLUNTAD", "MOTIVACIÓN", "MENTE", "EQUILIBRIO", 
        "TRABAJO", "ENERGÍA", "INNOVACIÓN", "ESTILO", "PASIÓN", "PERSEVERAR", "CRECIMIENTO", "SABER", 
        "FUERZA", "FAMILIA", "AMIGOS", "ENTUSIASMO", "VISIÓN", "DESTINO", "TRABAJO", "OPTIMISMO", 
        "SENTIMIENTO", "PODER", "METAS", "MOTIVACIÓN", "SINCERO", "ESPERANZA", "ESTABILIDAD", "PAZ"
        ],
      SWAHILI: [
        "UPENDO", "AMANI", "FURAHA", "MATUMAINI", "UJASIRI", "FAMILIA", "TUMAINI", "WAKATI", 
        "JUHUDI", "MAISHA", "NDOTO", "UHURU", "URAFIKI", "UZIMA", "FURAHA", "URAFIKI", 
        "JUA", "NURU", "BUSARA", "MAENDELEO", "LENGO", "CHANGAMOTO", "IMANI", "SHAUKU", 
        "KUUNDA", "MWANZO", "UZOEFU", "IMANI", "UVUMILIVU", "UTUKUFU", "UREMBO", "ROHO", 
        "MOYO", "MAAMUZI", "HEKIMA", "NGUVU", "MIRATHI", "FURAHA", "NURU", "NGUVU", 
        "PAMOJA", "NDUGU", "MOYO", "MAPENZI", "UWEZO", "MWENENDO", "AMANI", "MAENDELEO", 
        "KUJIVUNIA", "NGUVU", "USAWA", "HEKIMA", "SHUKRANI", "FARAJA", "UPENDO", "MSHIKAMANO", 
        "SHUGHULI", "MOYO", "KUJITOLEA", "MTINDO", "HALI", "USALAMA", "UJUZI", "UCHUMI", 
        "UFAHAMU", "VIWANGO", "MAFANIKIO", "UTULIVU", "MAONO", "UBUNIFU", "TIJA", "RAHA", 
        "MWANGA", "MATOLEO", "MAJUKUMU", "MISINGI", "SHIKAMOO", "UTANDAWAZI", "HALI", "KWA"
        ],
      FRENCH: [
        "AMOUR", "PAIX", "BONHEUR", "AVENIR", "COURAGE", "FAMILLE", "ESPOIR", "TEMPS", "EFFORT", 
        "VIE", "RÊVE", "LIBERTÉ", "AMITIÉ", "ÂME", "JOIE", "AMITIÉ", "LUMIÈRE", "SOLEIL", 
        "SAGESSE", "CROISSANCE", "OBJECTIF", "DÉFI", "FOI", "PASSION", "CRÉER", "DÉPART", 
        "EXPÉRIENCE", "CONFIANCE", "PERSÉVÉRANCE", "GLOIRE", "BEAUTÉ", "ÂME", "CŒUR", 
        "DÉCISION", "SAGESSE", "VOLONTÉ", "HÉRITAGE", "CLARTÉ", "MIRACLE", "AMOUR", "CULTURE", 
        "BONHEUR", "TOUJOURS", "ESPOIR", "COURAGE", "BRILLANCE", "FORCE", "PURETÉ", "AFFECTION",
        "COMPAGNIE", "RÉALISATION", "CONFIANCE", "AMOUR", "DÉTENTE", "UNION", "CIELO", 
        "HARMONIE", "JOIE", "LIBERTÉ", "SÉRÉNITÉ", "RÉUSSITE", "PARTAGE", "RÉFLEXION", "BIENVEILLANCE", 
        "SOUTIEN", "SAVOIR", "SOLIDARITÉ", "SIMPLICITÉ", "CONNAISSANCE", "RÉCONFORT", "SAISON", 
        "AMOUR", "PLAISIR", "MÉMOIRE", "RÉALITÉ", "PARTENARIAT", "BIEN-ÊTRE", "SOUTIEN", "RÉFLEXION", 
        "HARMONIE", "COMPLICE", "ACCORD", "Fierté", "RESPONSABILITÉ", "COMPÉTENCE", "JOIE", 
        "BONTÉ", "MÉLANGE", "DYNAMISME", "SOURIRE", "PARTAGE", "RECONNAISSANCE", "ÉQUILIBRE", 
        "CROISSANCE", "EXCELLENCE", "LÉGÈRETÉ", "SAVOIR", "VÉRITÉ", "ÉNERGIE", "CRÉATION", 
        "CÉLÉBRATION", "RÉUSSITE", "FORCE", "DÉCOUVERTE", "RÉSEAU", "VALEUR", "SUCCÈS"
      ]
  };